### ISSUE TITLE
Docker-Compose config idea

### ISSUE THREAD

**Issue by 6r1d** [XRFoundation/DigitalBeing#210]
Hello. I was installing DigitalBeing and had some issues. I'd make PR, but want to know what others think first, because I barely understand the project's internals.

DockerHub [shows](https://hub.docker.com/_/postgres) a bit more config options for Postgres than currently are used.
My approach here would be not to expect the user to configure things manually as it's told in the readme [step 7](https://github.com/XRFoundation/DigitalBeing/commit/04369602bf6bf145503dd1fd211600ab45570230#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), but to have a preconfigured Postgres instance instead.

[This](https://github.com/XRFoundation/DigitalBeing/commit/34b77e8b9d5ec20cb7784813ba67b77a1517e8ef) is what we have for Docker now:

```yaml
  db:
    image: postgres 
```

Instead, we can configure `docker-compose.yml` with some defaults:

```yaml
  db:
    restart: always
    image: postgres
    hostname: digitalbeing_db
    environment:
      POSTGRES_DB: digitalbeing
      POSTGRES_USER: digitalbeing
      POSTGRES_PASSWORD: digitalbeing_default_pw
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
```

and have a "starter" SQL file as well, instead of making the user manually do the parts of the installation process.

```sql
-- init.sql
GRANT ALL PRIVILEGES ON DATABASE digitalbeing TO digitalbeing;
CREATE TABLE chat_history(client_name text, chat_id text, message_id text, global_message_id text, sender text, content text);
```
